trigger:
  - master  # Adjust if your default branch is different

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.8'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Set Python version'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python your_script.py  # Replace with your actual script
    displayName: 'Run data processing script'
